on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: Build and Release Web
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Build
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_BOT_TOKEN }}
          external_repository: kw214/kw214.github.io
          publish_branch: main
          publish_dir: ./dist
          cname: kimmy.me
